#version: '3.8'

services:

  app:
    build: .
    container_name: mks-backend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis

  db:
    image: mysql:8.0
    restart: always
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: mks-backend
      MYSQL_DATABASE: mks-backend
      MYSQL_PASSWORD: mks-backend
    #volumes:
    # - dados-mysql:/var/lib/mysql
    ports:
      - "3306:3306"

  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
      - "6379:6379"
